version: '3.9'

services:
  postgres:
    image: postgres:14.15-alpine3.21
    ports:
      - 5555:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=swam
